# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'Kingfisher', '~> 7.0'
  pod "GCDWebServer", "~> 3.0"
  pod 'Cache', :git => 'https://github.com/hyperoslo/Cache.git'

  pre_install do |installer|
    # Define minimum deployment targets
    ios_deployment_target = '12.0'
    
    # Set minimum deployment targets for all pods
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = ios_deployment_target
    end
  end

  
  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
